server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    book-service: /books/**
    film-service: /films/**

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA-SERVER_PORT_8761_TCP_ADDR}:8761/eureka/
  instance:
    preferIpAddress: true
